# Generated by Django 3.0.8 on 2020-07-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkdx_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='type1',
            field=models.TextField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type2',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
