name: Test Runner Workflow

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  test_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd client && npm ci && npm run test
